Unset -e in run-parallel script wrapper

diff --git a/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.0_dont-use-var-lock.patch b/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.0_dont-use-var-lock.patch
--- a/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.0_dont-use-var-lock.patch
+++ b/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.0_dont-use-var-lock.patch
@@ -1,5 +1,5 @@
 diff --git a/tensorflow/tools/ci_build/gpu_build/parallel_gpu_execute.sh b/tensorflow/tools/ci_build/gpu_build/parallel_gpu_execute.sh
-index ee70f2f608b..347b984a6c7 100755
+index ee70f2f608b..ab5cbe7d7b5 100755
 --- a/tensorflow/tools/ci_build/gpu_build/parallel_gpu_execute.sh
 +++ b/tensorflow/tools/ci_build/gpu_build/parallel_gpu_execute.sh
 @@ -53,7 +53,7 @@ TEST_BINARY="$(rlocation $TEST_WORKSPACE/${1#./})"
@@ -20,3 +20,18 @@ index ee70f2f608b..347b984a6c7 100755
      if flock -n "$lock_fd";
      then
        (
+@@ -70,6 +70,7 @@ for j in `seq 0 $((TF_TESTS_PER_GPU-1))`; do
+         export CUDA_VISIBLE_DEVICES=$i
+         export HIP_VISIBLE_DEVICES=$i
+         echo "Running test $TEST_BINARY $* on GPU $CUDA_VISIBLE_DEVICES"
++        set +e
+         "$TEST_BINARY" $@
+       )
+       return_code=$?
+@@ -79,5 +80,5 @@ for j in `seq 0 $((TF_TESTS_PER_GPU-1))`; do
+   done
+ done
+ 
+-echo "Cannot find a free GPU to run the test $* on, exiting with failure..."
++echo "Cannot find a free GPU to run the test $TEST_BINARY $* on, exiting with failure..."
+ exit 1
