update patch - error no key

diff --git a/easybuild/easyconfigs/m/ModPipe/Modeller-10.7_install-to-modpipe.patch b/easybuild/easyconfigs/m/ModPipe/Modeller-10.7_install-to-modpipe.patch
--- a/easybuild/easyconfigs/m/ModPipe/Modeller-10.7_install-to-modpipe.patch
+++ b/easybuild/easyconfigs/m/ModPipe/Modeller-10.7_install-to-modpipe.patch
@@ -30,15 +30,19 @@ Update for ModPipe: Pavel Tomanek (Inuits)
     MODINSTALL=$DEFmodinstall
  fi
  if [ ! -d $MODINSTALL ] ; then
-@@ -103,7 +97,6 @@
+@@ -103,7 +97,10 @@
  echo
  echo "License key, obtained from our academic license server at"
  printf "https://salilab.org/modeller/registration.html: "
 -read KEY_MODELLER
++if [ -z "${KEY_MODELLER}" ]; then
++    echo 'ERROR: $KEY_MODELLER environment variable not set, should provide Modeller license key' >&2
++    exit 1
++fi
  
  
  echo
-@@ -118,7 +111,6 @@
+@@ -118,7 +115,6 @@
  echo "If they are incorrect, abort installation (ctrl-c) and run Install again."
  echo
  printf "Press <Enter> to begin the installation: "
@@ -46,7 +50,7 @@ Update for ModPipe: Pavel Tomanek (Inuits)
  echo
  echo "------------------------------------------------------------------------"
  echo
-@@ -153,7 +145,6 @@
+@@ -153,7 +149,6 @@
  echo "license = '${KEY_MODELLER}'" >> ${config}
  echo "Installation complete."
  printf "Press <Enter> to continue: "
@@ -54,7 +58,7 @@ Update for ModPipe: Pavel Tomanek (Inuits)
  
  echo
  echo "------------------------------------------------------------------------"
-@@ -180,7 +171,6 @@
+@@ -180,7 +175,6 @@
  echo "------------------------------------------------------------------------"
  echo
  printf "Press <Enter> to continue: "
