extend ictce patch for NCBI

diff --git a/easybuild/easyconfigs/n/NCBI-Toolkit/NCBI-Toolkit-9.0.0_ictce-fixes.patch b/easybuild/easyconfigs/n/NCBI-Toolkit/NCBI-Toolkit-9.0.0_ictce-fixes.patch
--- a/easybuild/easyconfigs/n/NCBI-Toolkit/NCBI-Toolkit-9.0.0_ictce-fixes.patch
+++ b/easybuild/easyconfigs/n/NCBI-Toolkit/NCBI-Toolkit-9.0.0_ictce-fixes.patch
@@ -1,6 +1,6 @@
 diff -ur ncbi_cxx--9_0_0.orig/src/build-system/configure ncbi_cxx--9_0_0/src/build-system/configure
 --- ncbi_cxx--9_0_0.orig/src/build-system/configure	2012-03-28 22:49:37.000000000 +0200
-+++ ncbi_cxx--9_0_0/src/build-system/configure	2013-01-18 11:17:35.302229258 +0100
++++ ncbi_cxx--9_0_0/src/build-system/configure	2013-01-18 13:50:58.301058922 +0100
 @@ -4621,7 +4621,7 @@
     compiler_ver="$icc_ver"
     compiler="ICC"
@@ -10,3 +10,12 @@ diff -ur ncbi_cxx--9_0_0.orig/src/build-system/configure ncbi_cxx--9_0_0/src/bui
               WithFeatures="$WithFeatures${WithFeaturesSep}ICC"; WithFeaturesSep=" "
  elif test "$VAC" = "yes" ; then
     compiler_ver="$vac_ver"
+@@ -5444,6 +5444,8 @@
+     mips-sgi-irix*:KCC )
+       ARCH_CFLAGS="-64"
+       ;;
++    *:ICC)
++      ;;
+     * )
+       { { echo "$as_me:$LINENO: error: Do not know how to compile 64-bit with compiler $CXX $compiler_ver $host:$compiler" >&5
+ echo "$as_me: error: Do not know how to compile 64-bit with compiler $CXX $compiler_ver $host:$compiler" >&2;}
