modified:   easybuild/easyconfigs/f/FSL/FSL-6.0.1_fslpython.patch

diff --git a/easybuild/easyconfigs/f/FSL/FSL-6.0.1_fslpython.patch b/easybuild/easyconfigs/f/FSL/FSL-6.0.1_fslpython.patch
--- a/easybuild/easyconfigs/f/FSL/FSL-6.0.1_fslpython.patch
+++ b/easybuild/easyconfigs/f/FSL/FSL-6.0.1_fslpython.patch
@@ -1,5 +1,5 @@
---- fslpython_install.sh.orig	2019-02-21 03:24:09.000000000 -0800
-+++ fslpython_install.sh	2019-04-24 15:11:02.000000000 -0700
+--- fsl/etc/fslconf/fslpython_install.sh.orig	2019-02-21 03:24:09.000000000 -0800
++++ fsl/etc/fslconf/fslpython_install.sh	2019-04-25 22:04:35.000000000 -0700
 @@ -30,9 +30,9 @@
  dropprivileges=0
  
@@ -13,7 +13,26 @@
  
  function syntax {
      echo "fslpython_install.sh [-f <FSLDIR>] [-q]"
-@@ -197,8 +197,11 @@
+@@ -59,7 +59,7 @@
+ shift $((OPTIND-1))
+ 
+ [ "$1" = "--" ] && shift
+-
++fsl_dir=${HOME}
+ if [ -z "${fsl_dir}" ]; then
+     if [ -z "${FSLDIR}" ]; then
+         echo "Error - FSLDIR not given as an argument and \$FSLDIR not set!" >&2
+@@ -70,8 +70,7 @@
+ fi
+ 
+ if [ ! -e "${fsl_dir}/bin" ]; then
+-    echo "Error - ${fsl_dir}/bin does not exist!" >&2
+-    exit 1
++    mkdir ${fsl_dir}/bin
+ fi
+ 
+ if [ ! -w "${fsl_dir}" ]; then
+@@ -197,8 +196,11 @@
  if [ ${quiet} -ne 1 ]; then
      echo "Stage 2"
  fi
@@ -26,7 +45,7 @@
      2>> "${miniconda_install_log}" | \
      ${script_dir}/progress.sh 133 ${quiet} 1>> "${miniconda_install_log}"
  if [ $? -ne 0 ]; then
-@@ -219,9 +222,36 @@
+@@ -219,9 +221,36 @@
    ln -sf "${fslpython_env_dir}/bin/python" "${fsl_dir}/bin/fslpythonw"
  fi
  
