modified:   easybuild/easyconfigs/f/FSL/FSL-6.0.1-iimkl-2018.3.222.eb 	modified:   easybuild/easyconfigs/f/FSL/FSL-6.0.1_fslpython.patch

diff --git a/easybuild/easyconfigs/f/FSL/FSL-6.0.1_fslpython.patch b/easybuild/easyconfigs/f/FSL/FSL-6.0.1_fslpython.patch
--- a/easybuild/easyconfigs/f/FSL/FSL-6.0.1_fslpython.patch
+++ b/easybuild/easyconfigs/f/FSL/FSL-6.0.1_fslpython.patch
@@ -1,5 +1,5 @@
---- fsl/etc/fslconf/fslpython_install.sh.orig	2019-02-21 03:24:09.000000000 -0800
-+++ fsl/etc/fslconf/fslpython_install.sh	2019-04-25 22:04:35.000000000 -0700
+--- fsl/etc/fslconf/fslpython_install.sh.orig	2019-04-29 22:26:48.355659475 +0000
++++ fsl/etc/fslconf/fslpython_install.sh	2019-04-29 22:34:54.998471111 +0000
 @@ -30,9 +30,9 @@
  dropprivileges=0
  
@@ -32,7 +32,17 @@
  fi
  
  if [ ! -w "${fsl_dir}" ]; then
-@@ -197,8 +196,11 @@
+@@ -85,8 +84,7 @@
+ fi
+ 
+ if [  -e "${fsl_dir}/fslpython" ]; then
+-    echo "Error - ${fsl_dir}/fslpython already exists!" >&2
+-    exit 1
++    mkdir mkdir ${fsl_dir}/fslpython
+ fi
+ 
+ 
+@@ -197,8 +195,11 @@
  if [ ${quiet} -ne 1 ]; then
      echo "Stage 2"
  fi
@@ -45,7 +55,7 @@
      2>> "${miniconda_install_log}" | \
      ${script_dir}/progress.sh 133 ${quiet} 1>> "${miniconda_install_log}"
  if [ $? -ne 0 ]; then
-@@ -219,9 +221,36 @@
+@@ -219,9 +220,36 @@
    ln -sf "${fslpython_env_dir}/bin/python" "${fsl_dir}/bin/fslpythonw"
  fi
  
