Fix dalton.in patch to be able to run tests from the build dir. And run tests...

diff --git a/easybuild/easyconfigs/d/Dalton/Dalton-2020.0_use-EB-install-for-dalton-script.patch b/easybuild/easyconfigs/d/Dalton/Dalton-2020.0_use-EB-install-for-dalton-script.patch
--- a/easybuild/easyconfigs/d/Dalton/Dalton-2020.0_use-EB-install-for-dalton-script.patch
+++ b/easybuild/easyconfigs/d/Dalton/Dalton-2020.0_use-EB-install-for-dalton-script.patch
@@ -3,8 +3,8 @@
 #
 # Åke Sandgren
 diff -ru dalton.orig/dalton.in dalton/dalton.in
---- dalton.orig/dalton.in	2021-10-05 13:33:25.000000000 +0200
-+++ dalton/dalton.in	2021-10-05 13:41:38.244136976 +0200
+--- dalton.orig/dalton.in	2021-10-05 14:33:14.000000000 +0200
++++ dalton/dalton.in	2021-10-15 12:45:56.751803496 +0200
 @@ -16,17 +16,7 @@
  dalton="dalton"
  DALTON="DALTON"
@@ -24,12 +24,20 @@ diff -ru dalton.orig/dalton.in dalton/dalton.in
  
  ## If your computer ressource uses modules, then you can make sure the right modules are loaded
  ## by uncommenting and adapting the two lines starting with #module following this comment.
-@@ -38,7 +28,7 @@
+@@ -38,7 +28,15 @@
  #module purge
  #module load python intel openmpi-i8
  
 -DALTON_EXECUTABLE=$SCRIPT_DIR/$dalton.x
-+DALTON_EXECUTABLE=$SCRIPT_DIR/bin/$dalton.x
++if [ -e "$SCRIPT_DIR/bin/$dalton.x" ]; then
++    DALTON_EXECUTABLE=$SCRIPT_DIR/bin/$dalton.x
++elif [ -e "$SCRIPT_DIR/$dalton.x" ]; then
++    # To make sure we can run tests from the build dir
++    DALTON_EXECUTABLE=$SCRIPT_DIR/$dalton.x
++else
++    echo "$dalton.x not found in $SCRIPT_DIR nor in $SCRIPT_DIR/bin"
++    exit 1
++fi
  
  which mpirun > /dev/null # check if mpirun exists, if not, then assume mpiexec
  if [ $? -eq 0 ]; then
