Switch to manually attempting merge due to github race condition with pull_request_target

diff --git a/.github/workflows/tagbot.yml b/.github/workflows/tagbot.yml
--- a/.github/workflows/tagbot.yml
+++ b/.github/workflows/tagbot.yml
@@ -3,7 +3,8 @@ on: [pull_request_target]
 
 jobs:
   tagbot:
-    if: github.event.pull_request.merge_commit_sha
+    # Note: can't rely on github.event.pull_request.merge_commit_sha because pull_request_target
+    # does not wait github mergability check, and the value is outdated.
     runs-on: ubuntu-24.04
     permissions:
       pull-requests: write
@@ -14,9 +15,21 @@ jobs:
     - name: Checkout PR for computing diff
       uses: actions/checkout@v4
       with:
-        ref: "${{ github.event.pull_request.merge_commit_sha }}"
+        ref: "${{ github.event.pull_request.head.sha }}"
         path: 'pr'
         fetch-depth: 0
+        
+   - name: Attempt Merge
+     id: merge
+     run: |
+       git merge --no-commit --no-ff origin/${{ github.event.pull_request.base.ref }}
+     continue-on-error: true
+
+   - name: Check merge result
+     if: steps.merge.outcome == 'failure'
+     run: |
+       echo "Merge conflict detected, failing job."
+       exit 1
 
     - name: set up Python
       uses: actions/setup-python@v5
