Fix indentation

diff --git a/.github/workflows/tagbot.yml b/.github/workflows/tagbot.yml
--- a/.github/workflows/tagbot.yml
+++ b/.github/workflows/tagbot.yml
@@ -23,17 +23,17 @@ jobs:
         path: 'pr'
         fetch-depth: 0
         
-   - name: Attempt Merge
-     id: merge
-     run: |
-       git merge --no-commit --no-ff origin/${{ github.event.pull_request.base.ref }}
-     continue-on-error: true
+    - name: Attempt Merge
+      id: merge
+      run: |
+        git merge --no-commit --no-ff origin/${{ github.event.pull_request.base.ref }}
+      continue-on-error: true
 
-   - name: Check merge result
-     if: steps.merge.outcome == 'failure'
-     run: |
-       echo "Merge conflict detected, failing job."
-       exit 1
+    - name: Check merge result
+      if: steps.merge.outcome == 'failure'
+      run: |
+        echo "Merge conflict detected, failing job."
+        exit 1
 
     - name: set up Python
       uses: actions/setup-python@v5
