Uncomment running test suite

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -139,7 +139,7 @@ jobs:
           # if tests failed, print error message that is picked up by boegelbot to determine end of test output
           sudo du -sch /home/* | sort -nr
           echo "Running test suite..."
-          #python -O -m test.easyconfigs.suite || (echo "ERROR: Not all tests were successful" && exit 1)
+          python -O -m test.easyconfigs.suite || (echo "ERROR: Not all tests were successful" && exit 1)
           df -h
           echo "Done running test suite."
 
